### ISSUE TITLE
Link in Understanding Components of Cadence Architecture blog gives 404 Error

### ISSUE THREAD

**Issue by sharanf** [uber/Cadence-Docs#152]
Clicking on the following link in the blog post [https://cadenceworkflow.io/blog/2023/07/01/components-of-cadence-application-setup/](url). gives a 404 error (see attached screenshot)

**You can follow the instructions provided [here](https://cadenceworkflow.io/docs/01-get-started/01-server-installation.html).**

![Screenshot 2023-07-12 at 11 30 48 (2)](https://github.com/uber/Cadence-Docs/assets/20459978/7b09b9ea-1177-4299-a098-aae749317d2a)

**Comment by chopincode** [comment]
This issue is resolved by https://github.com/uber/Cadence-Docs/pull/154. In the code base, it looks like we cannot reference files which are not in the same directory.
