### ISSUE TITLE
Update/fix dynamic config list

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence-docs#24]
* some of the items are no longer valid, need to remove
* some items are missing default values
* there are some new items added recently: check https://github.com/uber/cadence/blob/master/common/service/dynamicconfig/constants.go
* Add Supported Version and Deprecated Since versions for each config

**Comment by longquanzheng** [comment]
https://github.com/uber/cadence/pull/4053

**Comment by longquanzheng** [comment]
will fix in https://github.com/uber/cadence-docs/pull/41

**Comment by just-at-uber** [comment]
Is this still an issue @longquanzheng ?

**Comment by longquanzheng** [comment]
Not anymore. Thanks for reminding.
