### ISSUE TITLE
Make page width to be more adaptive to browser

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence-docs#28]
<img width="1000" alt="Screen Shot 2021-03-18 at 2 26 54 PM" src="https://user-images.githubusercontent.com/4523955/111700074-248f2e80-87f6-11eb-8c4e-f28b9d2be0ff.png">

Is it possible to make the width of the page more adaptive? @just-at-uber

**Comment by just-at-uber** [comment]
This is rendered in a table, i don't think there is much you can change here without changing to the format which vuepress uses for their configs:
https://vuepress.vuejs.org/config/#basic-config

**Comment by just-at-uber** [comment]
https://github.com/vuejs/vuepress/edit/master/packages/docs/docs/config/README.md

**Comment by longquanzheng** [comment]
> This is rendered in a table, i don't think there is much you can change here without changing to the format which vuepress uses for their configs:
> https://vuepress.vuejs.org/config/#basic-config

We have almost 300 dynamic configurations and growing. Would it be a problem?

**Comment by just-at-uber** [comment]
There shouldn't be a word limit restriction for pages if that is the question. Also it will show in the left side navigation all config entries if users want to quickly scan for a particular config. When navigating to different pages, these items will collapse, so it will only be visible for users when they navigate to the config page.

If page size is the concern, it might make sense to split into smaller pages with common dynamic configs.

For example, have a separate page for:
- Shared Dynamic Configuration
- Frontend Dynamic Configuration
- Matching Dynamic Configuration
- etc.

**Comment by longquanzheng** [comment]
> There shouldn't be a word limit restriction for pages if that is the question. Also it will show in the left side navigation all config entries if users want to quickly scan for a particular config. When navigating to different pages, these items will collapse, so it will only be visible for users when they navigate to the config page.
> 
> If page size is the concern, it might make sense to split into smaller pages with common dynamic configs.
> 
> For example, have a separate page for:
> 
> * Shared Dynamic Configuration
> * Frontend Dynamic Configuration
> * Matching Dynamic Configuration
> * etc.

Okay, I will try that. Thanks Justin.

**Comment by longquanzheng** [comment]
Removing the table in https://github.com/uber/cadence-docs/pull/41

**Comment by Beyourself123345788900** [comment]
- - [ ]

**Comment by just-at-uber** [comment]
Is this still an issue @longquanzheng ?

**Comment by longquanzheng** [comment]
No we can close it now . Thanks Justin
