### ISSUE TITLE
use go-docs for dynamic configuration and static configuraiton 

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence-docs#33]
So that users can easily know which configuration are available in which versions.

Do this after this PR is released: https://github.com/uber/cadence/pull/4129

So that the go-docs will contain the exactly same information

**Comment by longquanzheng** [comment]
And make sure update the links after this PR is released:

https://github.com/uber/cadence/pull/4118

**Comment by longquanzheng** [comment]
https://github.com/uber/cadence-docs/pull/41

**Comment by just-at-uber** [comment]
Is this still an issue @longquanzheng ?

**Comment by longquanzheng** [comment]
Not anymore. Thanks for reminding.
