### ISSUE TITLE
documentation about how to add new search attribute in prod cluster

### ISSUE THREAD

**Issue by longquanzheng** [uber/cadence-docs#34]
https://cadenceworkflow.io/docs/concepts/search-workflows/#local-testing

this won't work in real cluster becuase there are more than 1 nodes.

So there are two steps:

1. Add the key to ElasitcSearch using CLI
2. Add the key in https://github.com/uber/cadence/blob/master/config/dynamicconfig/development_es.yaml

**Comment by longquanzheng** [comment]
https://github.com/uber/cadence-docs/pull/41

**Comment by just-at-uber** [comment]
Still an issue @longquanzheng ?

**Comment by longquanzheng** [comment]
Not anymore. Thanks for reminding.
