### ISSUE TITLE
Add more content to "Troubleshooting/Runbook" in Operation guide

### ISSUE THREAD

**Issue by longquanzheng** [uber/Cadence-Docs#43]
Some recommendation for dealing with different alerts/error/

https://cadenceworkflow.io/docs/operation-guide/troubleshooting

**Comment by ibarrajo** [comment]
I see you added the documentation [later that year](https://github.com/uber/Cadence-Docs/commits/master/src/docs/07-operation-guide/04-troubleshooting.md), thank you!

https://cadenceworkflow.io/docs/operation-guide/troubleshooting/#errors
