### ISSUE TITLE
Document update: cassandra visibility not required

### ISSUE THREAD

**Issue by longquanzheng** [uber/Cadence-Docs#51]
After https://github.com/uber/cadence/pull/4241 is released.

**Comment by just-at-uber** [comment]
Looks like uber/cadence#4241 (uber/cadence@208edf4) has been released as part of 0.22 release (currently latest released version). Do you know the changes that are required for docs to close this issue @longquanzheng ?

**Comment by ibarrajo** [comment]
@longquanzheng could you provide some documentation about the change?

It's been 3 years since the change was released, perhaps the change log is enough documentation.

I'm closing this issue, feel free to reopen if you feel it needs to be addressed.
